version: "2"
linters:
  enable:
    - gocritic
    - gosec
    - govet # on by default
    - ineffassign # on by default
    - misspell
    - staticcheck # on by default
    - unused # on by default
  disable:
    - errcheck
    - unconvert
    - unparam
  settings:
    staticcheck:
      checks:
        - all # Enable all checks by default
        - -ST1005 # error strings should not be capitalized / error strings should not end with punctuation or newlines
        - -ST1017 # don't use Yoda conditions
        - -ST1023 # should omit type string from declaration; it will be inferred from the right-hand side
        - -QF1008 # could remove embedded field "ObjectMeta" from selector
        - -QF1011 # could omit type string from declaration; it will be inferred from the right-hand side
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gofmt
